CREATE TABLE Roles (
  RoleID INT PRIMARY KEY IDENTITY(1,1),
  RoleName VARCHAR(50) UNIQUE NOT NULL
);

-- Create Users Table with Indexes
CREATE TABLE Users (
  UserID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  PasswordHash VARCHAR(255),
  DateOfBirth DATE,
  Gender CHAR(1),
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE(),
  IsAnonymized BIT DEFAULT 0,
  RoleID INT,
  CONSTRAINT FK_UserRole FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
);

-- Create Books Table with Indexes and Constraints
CREATE TABLE Books (
  ISBN VARCHAR(20) PRIMARY KEY NOT NULL,
  Title VARCHAR(255) NOT NULL,
  StockQuantity INT CHECK (StockQuantity >= 0),
  Price DECIMAL(10, 2),
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE()
);

-- Create Orders Table with Indexes
CREATE TABLE Orders (
  OrderID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  UserID UNIQUEIDENTIFIER NOT NULL,
  OrderDate DATETIME DEFAULT GETDATE(),
  ShippingAddress VARCHAR(255),
  ShippingCity VARCHAR(50),
  Status VARCHAR(50) DEFAULT 'Pending',
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE(), 
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE NO ACTION
);

-- Create OrderLine Table with Indexes
CREATE TABLE OrderLine (
  OrderLineID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  OrderID UNIQUEIDENTIFIER NOT NULL,
  ISBN VARCHAR(20),
  Quantity INT CHECK (Quantity > 0),
  UnitPrice DECIMAL(10, 2),
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE NO ACTION,
  FOREIGN KEY (ISBN) REFERENCES Books(ISBN) ON DELETE NO ACTION
);

-- Create Reviews Table with Indexes
CREATE TABLE Reviews (
  ReviewID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  UserID UNIQUEIDENTIFIER NOT NULL,
  ISBN VARCHAR(20),
  Rating INT CHECK (Rating BETWEEN 1 AND 5),
  Comment VARCHAR(2000),
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE(),
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE NO ACTION,
  FOREIGN KEY (ISBN) REFERENCES Books(ISBN)
);

-- Adding Indexes for performance optimization
CREATE INDEX IDX_Books_ISBN ON Books(ISBN);
CREATE INDEX IDX_Orders_UserID ON Orders(UserID);
CREATE INDEX IDX_OrderLine_OrderID ON OrderLine(OrderID);
CREATE INDEX IDX_OrderLine_ISBN ON OrderLine(ISBN);
CREATE INDEX IDX_Reviews_UserID ON Reviews(UserID);
CREATE INDEX IDX_Reviews_ISBN ON Reviews(ISBN);